### ISSUE TITLE
Cant get it working

### ISSUE THREAD

**Issue by vushu** [clojure-vim/async-clj-omni#20]
I cant seem to get it working, I have tried everything, but to no avail, 
I installed the plugin and deoplete setup as instructed:

let g:deoplete#keyword_patterns = {}
let g:deoplete#keyword_patterns.clojure = '[\w!$%&*+/:<=>?@\^_~\-\.#]*'
doing :checkhealth
  1 health#deoplete#check
  2 ========================================================================
  3 ## deoplete.nvim
  4   - OK: has("nvim") was successful
  5   - OK: exists("v:t_list") was successful
  6   - OK: has("timers") was successful
  7   - OK: has("python3") was successful
  8   - INFO: If you're still having problems, try the following commands:
  9     $ export NVIM_PYTHON_LOG_FILE=/tmp/log
 10     $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
 11     $ nvim
 12     $ cat /tmp/log_{PID}
 13     and then create an issue on github
 14 

nothing absolutely happens, when editing a clojure file, does this still work with current version of deoplete?

**Comment by SevereOverfl0w** [comment]
Unless something changed in the last week, all should be fine. To confirm, have you installed:

- vim-fireplace
- deoplete.nvim
- async-clj-omni

Have you got an nrepl started. Can you do `:Eval (+ 1 1)`?

**Comment by vushu** [comment]
Yes it works fine using vim-fireplace 
![image](https://user-images.githubusercontent.com/1658625/41206448-6fbdd5c4-6d04-11e8-9c69-eea4f3c9c3ae.png)

also on omni complemtion works using <C-x> <C-o> 
![image](https://user-images.githubusercontent.com/1658625/41206473-c453701c-6d04-11e8-9213-292673751c02.png)

Im not sure what more to do.

**Comment by SevereOverfl0w** [comment]
Do you have cider-nrepl installed? Which version?

**Comment by SevereOverfl0w** [comment]
A good way to check is to ensure that:

```
:echo fireplace#message({'op': 'cider-version'})
```

outputs something.

**Comment by vushu** [comment]
Ahh Thank you so much, the problem is as you expected I didn't install cider-nrepl
I created the ~/.lein/profiles.clj file and added:
 
{:user {:plugins [[cider/cider-nrepl "0.17.0"]]}} 

Cheers and many thanks for this awesome plugin!

**Comment by SevereOverfl0w** [comment]
Glad you got it working!
